/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sysml2oml;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import org.slf4j.Logger;

import com.beust.jcommander.JCommander;
import com.beust.jcommander.Parameter;

import com.opencsv.exceptions.CsvValidationException;

public class App {
	@Parameter(
			names = { "--input-path", "-i" }, 
			description = "Path to search for input", 
			required = true, 
			order = 1)
	private static List<String> inputPaths = new ArrayList<>();

	@Parameter(
			names = { "--supertypes-map", "-m" }, 
			description = "Path to search for input", 
			required = true, 
			order = 1)
	private static String map_file;

	@Parameter(
			names = { "--help", "-h" },
			description = "Displays summary of options",
			help = true,
			order = 7)
	private boolean help;

	public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws CsvValidationException, FileNotFoundException, IOException {
    	final App app = new App();
		final JCommander builder = JCommander.newBuilder().addObject(app).build();
		
		builder.parse(args);
		if (app.help) {
			builder.usage();
			return;
		}
		
		Logger logger = org.slf4j.LoggerFactory.getLogger(App.class);
				
		Taxonomy2Oml taxonomy2Oml = new Taxonomy2Oml(logger, inputPaths, map_file);
		
        System.out.println(taxonomy2Oml.run());
    }
}
